apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: matiasmartin-labs
  name: github-actions-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get","create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "create", "update", "patch", "delete"]
  
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "create", "update", "patch", "delete"]
