apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-manager-binding
  namespace: matiasmartin-labs
subjects:
  - kind: ServiceAccount
    name: default
    namespace: actions-runner-system
roleRef:
  kind: Role
  name: github-actions-manager
  apiGroup: rbac.authorization.k8s.io
